GET http://localhost:8080/auth/all
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiZjNhZTk0MTNmOWE0NzViODYxNjc1NjNjOTk3NzE0MSIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMjYzNjc4NiwibmJmIjoxNzMyNjM2Nzg2LCJleHAiOjE3MzI2MzY4NDZ9.mvTq92MYCS3yeKtpt_SWjuCQCPyDARUCCYeupcAYYzI