GET http://localhost:8080/players
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyZGUwNzE3MmQ4Yzk0MzVhYjI4MTdhZjI1MDIxMTJmNyIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMjY5MDczMSwibmJmIjoxNzMyNjkwNzMxLCJleHAiOjE3MzI2OTI1MzF9.qok0DsACAjvU-lmHIwg2k_Zad0UUy9JkCSyrRpW6uDI