GET http://localhost:8080/players
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxODE2NjU1MWYzM2Q0ZmVkOGQ5NGRiYTllNTIzNGRkMiIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0Njg2MTE4LCJuYmYiOjE3MzQ2ODYxMTgsImV4cCI6MTczNDY4NzkxOH0.z01PGTXYFskMIhD5Smg6lUEEI0kRilyIqfk0B6Yo53M