GET http://localhost:8080/players
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwNWMzNmZhM2VjMzQ0MmRkYTQyMjQzMmZkNDgyNDRlMSIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0Nzc3Njk3LCJuYmYiOjE3MzQ3Nzc2OTcsImV4cCI6MTczNDc3OTQ5N30.Mlm5IXdkVt1NrpEermT5o82Nz-Lv4kaeaA1QjogDbts