GET http://localhost:8080/teams
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxYjIwZjA4ZTNkNTY0MGRmODdjMjlmM2M5ZDkxZGM4YyIsInN1YiI6ImFkbWluIiwiaWF0IjoxNzM0OTY3NTM4LCJuYmYiOjE3MzQ5Njc1MzgsImV4cCI6MTczNDk2OTMzOH0.ym6wthGGOe9Ob6pC00lu7bEPPcO_t9xfn4QtFPukAo8