GET http://localhost:8080/teams
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhNjg5ODdkYzlmMzc0ZGZiOGM0NzFhMDBkNWQyNzI4NCIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMzQ3NTAzNiwibmJmIjoxNzMzNDc1MDM2LCJleHAiOjE3MzM0NzY4MzZ9.Ri_ezM8uQ_yfZG46aooMAfIbm3Jijy1m-5bDRKMqIgM