GET http://localhost:8080/users/all
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhOTgyM2M5NTBkY2Y0MGFkYjFiMjcyYzk2NDc5ODM5MSIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMjY4NjUyOSwibmJmIjoxNzMyNjg2NTI5LCJleHAiOjE3MzI2ODgzMjl9.Z8uMM7Yh0q7tOZnPQZM-m8ej-iHrgwmL7c1BWCt0QO4
