GET http://localhost:8080/users/all
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIzN2I4MGMxMGNlZTA0ZmMxYjRiZjkwNDU1NmE3NTc2ZCIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMzQ4Mjk3OCwibmJmIjoxNzMzNDgyOTc4LCJleHAiOjE3MzM0ODQ3Nzh9.1R5t7tcgkC3J7CnyOIOMnY2gkpNey2mh3GKEjROaiZ4
