GET http://localhost:8080/users/fromtoken
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlMWY4OTkwZDJjODA0OGVjYjg4NWIwNDJkMDJmZGQyZSIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0MTY2NTYxLCJuYmYiOjE3MzQxNjY1NjEsImV4cCI6MTczNDE2ODM2MX0.wDKjVYysj3Oek4kBNHHcJO093nfzN1D5_E_O0qXNE0s