GET http://localhost:8080/users/fromtoken
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJiODk2YjA5ZmFlY2Q0YjE5YTExZTA5NGY5YWQ5ZGUzNCIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMzQ4Mjg3NCwibmJmIjoxNzMzNDgyODc0LCJleHAiOjE3MzM0ODQ2NzR9.k5i1RxgLydLhK_JSlpF6jp-pnS9VWjYRjyLWApCIHUM