GET http://localhost:8080/users/all
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3Y2I5OTZhOWIzMDE0ZTliYTM2NjNkMDAxMjI1NzIyOCIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzMzNzc0NDQ0LCJuYmYiOjE3MzM3NzQ0NDQsImV4cCI6MTczMzc3NjI0NH0.nOBX5yr79WmCrM2m4HvY9znUedgumDbDxaEv-tDfbaU
