GET http://localhost:8080/users/fromtoken
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyOTNlZGU4YTBmY2Y0NmJiYTEzZjZhODEzYzY3YjRmNyIsInN1YiI6ImtpcmlsbDE4IiwiaWF0IjoxNzM0Nzc0NDQ5LCJuYmYiOjE3MzQ3NzQ0NDksImV4cCI6MTczNDc3NjI0OX0.ON6baZmpA7C4l55ATSRyOm4HQrYFgAJh-4b2VN4tPXY