PUT http://localhost:8080/pick/2/addPlayer/1
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJmN2VlMDI1MTZhNmE0ZjA1OTYwYjU0MDY0ZTVhNDY0NSIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0NzkyMjI5LCJuYmYiOjE3MzQ3OTIyMjksImV4cCI6MTczNDc5NDAyOX0.BfwrUl-Hz3WTzBlrSJNJiHZcAfi_H-_l4ytr5yh-dKM
