POST http://localhost:8080/team
Content-Type: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhYjUzYWZmMjA4MDY0MGNjOThlMzAyMWQ5NDhjZmU5MSIsInN1YiI6InZhZHppbSIsImlhdCI6MTczMzM5NTE0OSwibmJmIjoxNzMzMzk1MTQ5LCJleHAiOjE3MzMzOTY5NDl9.rmflAj7WdjRJYQGFzmDdt07bG82CvLdLqrot3qfTlNc

{
  "name": "olegi2",
  "points": 10,
  "price": 14
}
