POST http://localhost:8080/team
Content-Type: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDI1NTBlNzdkNzQ0M2Y3YjcxMmFmYWQxYTkwZGNiMiIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0NjgzODgwLCJuYmYiOjE3MzQ2ODM4ODAsImV4cCI6MTczNDY4NTY4MH0.VDUCs3zDzgSIoS5n60UrjqF-AX9XZeKoE9W6cO4Phek

{
  "name": "olegi2",
  "points": 10,
  "price": 14
}
