POST http://localhost:8080/player
Accept: application/json
Content-Type: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4Yzg3MjAyNzhlYzY0YjA0YmI5YzlhMmVlMTNmMDQ5ZSIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0OTM4MTI1LCJuYmYiOjE3MzQ5MzgxMjUsImV4cCI6MTczNDkzOTkyNX0.2ajlEjHttTUJFJL7EVNQwWaQKoSsIyzR_AKbTZXMkTk

{
  "name": "oleg",
  "price": 10,
  "points": 4,
  "team": {
    "id": 1
  }
}
