DELETE http://localhost:8080/pick/2/removePlayer/1
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJlMmUyMGM5NGM2OWM0ZWFlODQxNDI1MzA0YzMxMjE4ZiIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0Nzg2NTk1LCJuYmYiOjE3MzQ3ODY1OTUsImV4cCI6MTczNDc4ODM5NX0.V8_uxXVJtsOPcHNrOpUhw60uUdhhjgAJhUUn5-jDtQg