DELETE http://localhost:8080/pick/2/removePlayer/1
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI4Yzg3MjAyNzhlYzY0YjA0YmI5YzlhMmVlMTNmMDQ5ZSIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0OTM4MTI1LCJuYmYiOjE3MzQ5MzgxMjUsImV4cCI6MTczNDkzOTkyNX0.2ajlEjHttTUJFJL7EVNQwWaQKoSsIyzR_AKbTZXMkTk