DELETE http://localhost:8080/pick/2/removePlayer/1
Accept: application/json
x-csrf-token: _csrf
_csrf: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJhNGRiZDkwZDA4ZTg0YWRhYWIzMDc3Y2NiZGYyNDY2YiIsInN1YiI6ImtpcmlsbDE0IiwiaWF0IjoxNzM0Nzc5MDQwLCJuYmYiOjE3MzQ3NzkwNDAsImV4cCI6MTczNDc4MDg0MH0.koeSfk0k3z0dJuvophoLJTs7zG8KmfHwNHTydaqPmjU